### ISSUE TITLE
Bugged allie

### ISSUE THREAD

**Issue by ripjaw567** [Vladislav2437/EnchantedCustomRoles#4]
The following Scp is bugged when trying to add as ally: Scp173

![image](https://github.com/Vladislav2437/EnchantedCustomRoles/assets/61097944/fceff8b1-1eac-4bd7-96c2-5ed6545e84b0)
![image](https://github.com/Vladislav2437/EnchantedCustomRoles/assets/61097944/23bc1dd7-b2b6-4dfe-9e81-ea8983cc6c1e)

Testing utilizing 096 allowed the class to load in and work as intended.

**Comment by Vladislav2437** [comment]
thank you, i didn't see this, It will be fixed immediately
