### ISSUE TITLE
Enchancement:SpawnWaveLimit

### ISSUE THREAD

**Issue by nonatus** [Vladislav2437/EnchantedCustomRoles#5]
Limit for a wave of MTF, CI or other teams.

**Comment by Vladislav2437** [comment]
Can you repeat explaining what do you want?

**Comment by nonatus** [comment]
Other limit setting to set a limit of subclass in a spawn wave. 
Example: only 1 Juggernaut in a wave. In next wave he can spawn again.

**Comment by Vladislav2437** [comment]
And how can I then Properly use spawn limit?

**Comment by nonatus** [comment]
SpawnWaveLimit feature was in AdvancedSubclassing, so...
You can search it up in code of AdvancedSubclassing.
